CODE: 2b7e576abf649d - Command: set stars_count - Guild: 515159795473317889 - Time: 2019-11-10 16:32:30.858048
Traceback (most recent call last):

  File "/home/style/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 362, in _actual_conversion
    ret = await converter.convert(ctx, argument)

  File "/home/style/PycharmProjects/Rosie/Bot2/cogs/classes/converters.py", line 85, in convert
    if self.from_ < argument < self.to:

TypeError: '<' not supported between instances of 'int' and 'str'



CODE: ade2b4baaccc96 - Command: rose update guild - Guild: 515159795473317889 - Time: 2019-11-10 16:44:51.595753
Traceback (most recent call last):

  File "/home/style/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)

  File "/home/style/PycharmProjects/Rosie/Bot2/cogs/owner.py", line 171, in guild_
    z = await g.set(key, value)

  File "/home/style/PycharmProjects/Rosie/Bot2/cogs/classes/guild.py", line 79, in set
    z = await self.bot.db.execute(f"UPDATE {table} SET {key} = $1 WHERE guild_id = $2", value, self.id)

  File "/home/style/.local/lib/python3.6/site-packages/asyncpg/pool.py", line 509, in execute
    return await con.execute(query, *args, timeout=timeout)

  File "/home/style/.local/lib/python3.6/site-packages/asyncpg/connection.py", line 275, in execute
    _, status, _ = await self._execute(query, args, 0, timeout, True)

  File "/home/style/.local/lib/python3.6/site-packages/asyncpg/connection.py", line 1414, in _execute
    query, args, limit, timeout, return_status=return_status)

  File "/home/style/.local/lib/python3.6/site-packages/asyncpg/connection.py", line 1422, in __execute
    return await self._do_execute(query, executor, timeout)

  File "/home/style/.local/lib/python3.6/site-packages/asyncpg/connection.py", line 1444, in _do_execute
    result = await executor(stmt, None)

asyncpg.exceptions.InvalidTextRepresentationError: invalid input syntax for type json
DETAIL:  Token "'" is invalid.



CODE: 138c71fb686f01 - Command: osu - Guild: 538366293921759233 - Time: 2019-11-16 01:09:44.210528
Traceback (most recent call last):

  File "/home/style/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)

  File "/home/style/PycharmProjects/Rosie/Bot2/cogs/gamestats.py", line 219, in osu
    e = Embed(description=z, color=self.bot.color)

  File "/home/style/.local/lib/python3.6/site-packages/discord/embeds.py", line 113, in __init__
    self.colour = colour

  File "/home/style/.local/lib/python3.6/site-packages/discord/embeds.py", line 210, in colour
    raise TypeError('Expected discord.Colour, int, or Embed.Empty but received %s instead.' % value.__class__.__name__)

TypeError: Expected discord.Colour, int, or Embed.Empty but received str instead.



CODE: 714ccbf21b389a - Command: fortnite - Guild: 538366293921759233 - Time: 2019-11-16 01:19:05.695898
Traceback (most recent call last):

  File "/home/style/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)

  File "/home/style/PycharmProjects/Rosie/Bot2/cogs/gamestats.py", line 147, in fortnite
    z = f"**SOLO**\nWins: {solo.top1}\nTop 3: {solo.top3}\nTop 5: {solo.top5}\nTop 10: {solo.top10}\n" \

AttributeError: 'coroutine' object has no attribute 'top1'



